kauaicapstone/Controllers/LegendsController.cs
// Author: Rose Wisotzky
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kauaicapstone.Data;
using kauaicapstone.Models;
using kauaicapstone.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace kauaicapstone.Controllers
{
    [Authorize]
    public class LegendsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public LegendsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        //private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Legends
        // This method looks into the legends table and grabs the legends, including the User information, where the boolean value of IsApproved is set to true and saves that in a variable named applicationDbContext. It then returns that variable as a list passed into the Index view.
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Legend.Include(l => l.User).Where(l => l.IsApproved == true);
            return View(await applicationDbContext.ToListAsync());
        }

        //GET: PendingLegends
        //This method sorts through the legends in our database and selects the legends where the boolean value of IsApproved is set to false. We have the Distinct method on there so there are not any repeats. We then return the applicationDbContext that has been passed into our PendingIndex view.
        public async Task<IActionResult> PendingIndex()
        {
            var applicationDbContext = _context.Legend.Include(l => l.User).Where(l => l.IsApproved == false).Distinct();


            return View(await applicationDbContext.ToListAsync());

        }
        //GET: Approved Legends
        //This method changes the boolean value of IsApproved. We are passing in the legend id from our URL route as an argument in this method.
        public async Task<IActionResult> Approve([FromRoute] int id)
        {
            //We are using _context to go into our database and find the legend that has the same id as the one we are passing in.
            var legend = _context.Legend.Find(id);
            //If we can't find that legend, we will display a Not Found message.
            if (id != legend.LegendId)
            {
                return NotFound();
            }
            //ModelState is a property on the Controller class. The ModelState is a collection of key value pairs that get sent to the serer when a request is made. It will be valid if all of those pairs are true. If not, it will be invalid and the request will stop.
            if (ModelState.IsValid)
            {
                try
                {
                    //Once the ModelState is valid, the IsApproved is changed to true and then we call Update in our database to change that value and SaveChangesAsync() to save them.
                    legend.IsApproved = true;
                    _context.Update(legend);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LegendExists(legend.LegendId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", legend.UserId);
            return View(legend);
        }


        // GET: Legends/Details/5
        //This method gets the legends and their details! We pass in the id as an argument.
        public async Task<IActionResult> Details(int? id)
        {
            // Here we just check that the legend we are trying to target has an id--another way to check if it exists. If not, we return NotFound.
            if (id == null)
            {
                return NotFound();
            }
            //If the id is not null, we use _context to go through our database and get the legend with that id, and all of the corresponding information we want. ThenInclude allows us to go into our join table to reference the ViewLocation, which we will want when looking at our legend details.
            var legend = await _context.Legend
                .Include(l => l.User)
                .Include(l => l.LegendViewLocations)
                .ThenInclude(l => l.ViewLocation)
                .FirstOrDefaultAsync(m => m.LegendId == id)
                ;
            if (legend == null)
            {
                return NotFound();
            }

            return View(legend);
        }

        // GET: Legends/Create. 
        public IActionResult Create()
        {
            LocationsLegendViewModel location = new LocationsLegendViewModel() {
                AvailableLocations = _context.ViewLocation.Include(l => l.User).ToList()
            };



            return View(location);
        }
        //GET: Legends/CreateForm
        public IActionResult CreateForm(List<int> ViewLocationInput)
        {
            CreateLegendViewModel viewModel = new CreateLegendViewModel()
            {
                LocationIds = ViewLocationInput
            };
            return View(viewModel);
        }
        // POST: Legends/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EditLegendLocationViewModel viewModel, List<int> ViewLocationInput)
        {
            ModelState.Remove("Legend.UserId");
            ModelState.Remove("ViewLocationInput");
            ModelState.Remove("Legend.LegendViewLocations");
            if (ModelState.IsValid)
            {
                var legend = viewModel.Legend;
                //var legendViewLocations = _context.LegendViewLocation.Include(l => l.Legend.Title).Include(l=> l.ViewLocation.Name).ToList();
                //var legendViewName = legendViewLocations.Select(l => l.ViewLocation.Name);
                //var legendTitle = legendViewLocations.Select(l => l.Legend.Title);
                var currentUser = await _userManager.GetUserAsync(HttpContext.User);
                legend.UserId = currentUser.Id;
                viewModel.LocationIds = ViewLocationInput;
                _context.Add(legend);

                foreach (var id in ViewLocationInput)
                {


                    LegendViewLocation newView = new LegendViewLocation()
                    {
                        LegendId = legend.LegendId,
                        ViewLocationId = id,
                    };
                    _context.Add(newView);
                }


                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

        // GET: Legends/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (_userManager.GetUserAsync(User).Result.IsAdmin) 
    {
                if (id == null)
                {
                    return NotFound();
                }
                var viewLocationList = _context.LegendViewLocation.Where(lv => lv.LegendId == id).Select(lv => lv.ViewLocationId).ToList();

                EditLegendLocationViewModel location = new EditLegendLocationViewModel()
                {
                    AvailableLocations = _context.ViewLocation.Include(l => l.User).ToList(),
                    Legend = await _context.Legend.FindAsync(id),
                    LocationIds = viewLocationList

                };



                if (location == null)
                {
                    return NotFound();
                }
                ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", location.Legend.UserId);
                return View(location);
            } else
            {
                return NotFound();
            }
        }

        // POST: Legends/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditLegendLocationViewModel viewModel, List<int> ViewLocationInput)
        {
            if (_userManager.GetUserAsync(User).Result.IsAdmin)
            {
                if (id != viewModel.Legend.LegendId)
                {
                    return NotFound();
                }
                ModelState.Remove("User");
                ModelState.Remove("Legend.LegendViewLocations");
                if (ModelState.IsValid)
                {
                    List<LegendViewLocation> viewLocations = await _context.LegendViewLocation.Where(lv => lv.LegendId == id).ToListAsync();
                    viewLocations.ForEach(lv => _context.LegendViewLocation.Remove(lv));
                    try
                    {
                        var legend = viewModel.Legend;
                        viewModel.LocationIds = ViewLocationInput;
                        _context.Legend.Update(legend);

                        foreach (var item in ViewLocationInput)
                        {
                            LegendViewLocation newView = new LegendViewLocation()

kauaicapstone/Controllers/ViewLocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kauaicapstone.Data;
using kauaicapstone.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using kauaicapstone.Models.ViewModels;

namespace kauaicapstone.Controllers
{
    [Authorize]
    public class ViewLocationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;




        public ViewLocationsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)

        {
            _context = context;
            _userManager = userManager;

        }




        public IActionResult LegendsIndex()
        {
            return this.RedirectToAction("Create", "Legends");
        }
        // GET: ViewLocations
        public async Task<IActionResult> Index()
        {

            /*    var applicationDbContext = _context.ViewLocation.Include(v => v.Name).take(v => v.ViewPointAddress)*/

            return View(await _context.ViewLocation.ToListAsync());
        }

        public async Task<IActionResult> SearchIndex(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;


            var applicationDbContext = _context.ViewLocation.Where(v => v.Name.Contains(searchString));
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ViewLocations/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var viewLocation = await _context.ViewLocation
                .Include(v => v.User)
                .Include(v => v.Comments)
                .ThenInclude(v => v.User)
                .Include(v => v.LegendViewLocations)
                .ThenInclude(v => v.Legend)
                .FirstOrDefaultAsync(m => m.ViewLocationId == id);
            if (viewLocation == null)
            {
                return NotFound();
            }
            
            LocationCommentViewModel viewModel = new LocationCommentViewModel()
            {
                Location = viewLocation
            };
            return View(viewModel);
        }




        // GET: ViewLocations/Create
        public IActionResult Create()
        {
            {
                ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id");
                return View();
            }
        }

        // POST: ViewLocations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LocationsLegendViewModel viewModel, List<int> ViewLocationInput)
        {
            ModelState.Remove("ViewLocation.UserId");
            ModelState.Remove("ViewLocation.User");
            if (ModelState.IsValid)
            {
                var location = viewModel.ViewLocation;
                var currentUser = await _userManager.GetUserAsync(HttpContext.User);
                viewModel.ViewLocation.User = currentUser;
                viewModel.ViewLocation.UserId = currentUser.Id;
                _context.Add(location);
                foreach (var id in ViewLocationInput) {
                    LegendViewLocation newView = new LegendViewLocation()
                    {
                        ViewLocationId = location.ViewLocationId,

                    };
                }
                await _context.SaveChangesAsync();
                if (_userManager.GetUserAsync(User).Result.IsAdmin) {
                    return RedirectToAction(nameof(Index));
                } else { 
                    return RedirectToAction(nameof(LegendsIndex));
                    }
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", viewModel.ViewLocation.UserId);
            return View(viewModel);
        }

        // GET: ViewLocations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (_userManager.GetUserAsync(User).Result.IsAdmin)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var viewLocation = await _context.ViewLocation.FindAsync(id);
                if (viewLocation == null)
                {
                    return NotFound();
                }
                ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", viewLocation.UserId);
                return View(viewLocation);
        } else { 
        return NotFound();
    }
            }


        // POST: ViewLocations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ViewLocationId,Name,ViewPointAddress,UserId")] ViewLocation viewLocation)
        {
            if (_userManager.GetUserAsync(User).Result.IsAdmin)
            {
                if (id != viewLocation.ViewLocationId)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(viewLocation);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ViewLocationExists(viewLocation.ViewLocationId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", viewLocation.UserId);
                return View(viewLocation);
        } else {
        return NotFound();
    }
}


        // GET: ViewLocations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (_userManager.GetUserAsync(User).Result.IsAdmin)
            {
                var viewLocation = await _context.ViewLocation
                .Include(v => v.User)
                .FirstOrDefaultAsync(m => m.ViewLocationId == id);
                if (viewLocation == null)
                {
                    return NotFound();
                }

                return View(viewLocation);
            } else
            {
                return NotFound();
            }
        } 

        // POST: ViewLocations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var viewLocation = await _context.ViewLocation.FindAsync(id);
            _context.ViewLocation.Remove(viewLocation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ViewLocationExists(int id)
        {
            return _context.ViewLocation.Any(e => e.ViewLocationId == id);
        }
    }
}

kauaicapstone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - waimakua</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/waimakua.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/waimakua.css" />
</head>
@if (ViewData["Title"].ToString() != "Welcome")
{
<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3*@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">waimakua</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewLocations" asp-action="Index">locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Legends" asp-action="Index">legends</a>
                        </li>



                    </ul>
                    </div>
                </div>
            </nav>
            @if (ViewData["Title"].ToString() == "Index")
            {
                <div class="baby-search">
                    <div class="baby-search-text">
                        <p>where would you like to go?</p> <br/>
                    </div>
                    
                    <form asp-controller="ViewLocations" asp-action="SearchIndex" method="get">
                        <input type="text" placeholder="search locations" name="searchString" value="@ViewData["currentFilter"]" id="searchString" />
                        <input type="submit" value="search" class="btn btn-sm btn-info" asp-area="" asp-controller="ViewLocations" asp-action="SearchIndex" />
                    </form>
                </div>
            }
    </header>
        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - waimakua - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>
        </environment>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("Scripts", required: false)
    </body>
} else
{
<body>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
}
</html>